# -*- coding: utf-8 -*-
"""Python_Project1 - ying wu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xYWfMMmP-qqA7fEKXRPxK538E6bXm4og

In this project, I'm interested in looking at the Algebra2/Trigonometry Regents Exam mean score in Benjamin Cardozo High School and want to compare it with Bayside High School.
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/2014-15_To_2016-17_School-_Level_NYC_Regents_Report_For_All_Variables.csv')

df.head(30)

df.tail(30)

df.shape

df. isnull().sum()

df.dropna()

df[df['School Name'] == 'Benjamin N. Cardozo High School']

from matplotlib import pyplot as plt
_df_8['Total Tested'].plot(kind='hist', bins=20, title='Total Tested')
plt.gca().spines[['top', 'right',]].set_visible(False)

df[df['School Name'] == 'Bayside High School']

df.groupby(['School Name'])['Regents Exam','Mean Score'].count()

from matplotlib import pyplot as plt
_df_14['Regents Exam'].plot(kind='hist', bins=20, title='Regents Exam')
plt.gca().spines[['top', 'right',]].set_visible(False)

df = df[(df['School Name'] == 'Benjamin N. Cardozo High School')&(df['Mean Score'] == 'Algebra2/Trigonometry')]

print(df)

"""I would like to extract the Algebra2/Trigonometry Regents Exam mean score for Benjamin and Cardozo High School from the dataset, but no result returned."""

